// Auto-generated by deploy_site.py — do not edit manually
window.__REPORT_LIST__ = [
  {
    "date": "20260524",
    "label": "2026年05月24日",
    "file": "reports/CLS_早报_20260524.html"
  },
  {
    "date": "20260522",
    "label": "2026年05月22日",
    "file": "reports/CLS_早报_20260522.html"
  },
  {
    "date": "20260521",
    "label": "2026年05月21日",
    "file": "reports/CLS_早报_20260521.html"
  },
  {
    "date": "20260520",
    "label": "2026年05月20日",
    "file": "reports/CLS_早报_20260520.html"
  }
];
