// Auto-generated by deploy_site.py — do not edit manually
window.__REPORT_LIST__ = [
  {
    "date": "20260531",
    "label": "2026年05月31日",
    "file": "reports/CLS_早报_20260531.html"
  },
  {
    "date": "20260529",
    "label": "2026年05月29日",
    "file": "reports/CLS_早报_20260529.html"
  },
  {
    "date": "20260528",
    "label": "2026年05月28日",
    "file": "reports/CLS_早报_20260528.html"
  },
  {
    "date": "20260527",
    "label": "2026年05月27日",
    "file": "reports/CLS_早报_20260527.html"
  },
  {
    "date": "20260526",
    "label": "2026年05月26日",
    "file": "reports/CLS_早报_20260526.html"
  },
  {
    "date": "20260525",
    "label": "2026年05月25日",
    "file": "reports/CLS_早报_20260525.html"
  },
  {
    "date": "20260524",
    "label": "2026年05月24日",
    "file": "reports/CLS_早报_20260524.html"
  },
  {
    "date": "20260522",
    "label": "2026年05月22日",
    "file": "reports/CLS_早报_20260522.html"
  },
  {
    "date": "20260521",
    "label": "2026年05月21日",
    "file": "reports/CLS_早报_20260521.html"
  },
  {
    "date": "20260520",
    "label": "2026年05月20日",
    "file": "reports/CLS_早报_20260520.html"
  }
];
